import CustomLayout from '@/components/antd/CustomLayout'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CustomHeader from '@/components/antd/CustomHeader'
import CustomMenu from '@/components/antd/CustomMenu'
import CustomContent from '@/components/antd/CustomContent'
import CustomFooter from '@/components/antd/CustomFooter'
import { CustomText } from '@/components/antd/CustomTypography'
import ConditionalComponent from '@/components/ConditionalComponent'
import Fallback from '@/components/Fallback'
import { useState, useEffect } from 'react'
import CustomAntProvider from '@/components/antd/CustomAntProvider'
import GlobalStyle from '@/themes/GlobalStyle'
import ErrorBoundary from 'antd/es/alert/ErrorBoundary'
import { ThemeProvider } from 'styled-components'
import { defaultTheme } from '@/themes/themes'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <ConditionalComponent condition={true} fallback={<Fallback />}>
          <CustomAntProvider>
            <ErrorBoundary>
              <CustomLayout>
                <div>{children}</div>
              </CustomLayout>
            </ErrorBoundary>
          </CustomAntProvider>
        </ConditionalComponent>
      </body>
    </html>
  )
}
